# Generated by Django 3.2.23 on 2023-12-12 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0002_auto_20231212_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='LOGIN',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dos.login'),
            preserve_default=False,
        ),
    ]
