# Generated by Django 3.2.23 on 2023-12-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0003_branch_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Balance_Amount',
            new_name='Amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='FROM_ID',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='TO_ID',
        ),
        migrations.AddField(
            model_name='account_details',
            name='Balance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account_details',
            name='pin_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='ACC_NO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dos.account_details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='Transaction_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='Type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
