# Generated by Django 3.2.23 on 2023-12-20 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0004_auto_20231212_0510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='request_table',
        ),
    ]
