# Generated by Django 3.2.23 on 2024-03-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0006_auto_20240208_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
