# Generated by Django 3.2.23 on 2024-03-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0007_log_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='block_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
            ],
        ),
    ]
