# Generated by Django 3.2.23 on 2023-12-12 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_details',
            name='BRANCH',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dos.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report_table',
            name='report',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('BRANCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dos.branch')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dos.user')),
            ],
        ),
    ]
